package=native_rust
$(package)_version=1.75.0
$(package)_download_path=https://static.rust-lang.org/dist/2023-12-28
$(package)_file_name=rustc-1.75.0-src.tar.xz

# Official Upstream SHA256 Sums (Verified from static.rust-lang.org/dist/2023-12-28)
$(package)_sha256_hash=4526f786d673e4859ff2afa0bab2ba13c918b796519a25c1acce06dba9542340

# Bootstrap compiler (Linux x86_64) - Source build verified
$(package)_bootstrap_file_linux=rust-1.75.0-x86_64-unknown-linux-gnu.tar.gz
$(package)_bootstrap_sha256_linux=473978b6f8ff216389f9e89315211c6b683cf95a966196e7914b46e8cf0d74f6

# Bootstrap compiler (macOS) - Binary bootstrap used for host compatibility
# Note: macOS/iOS builds use verified upstream binaries as Stage 0 and skip source rebuild
# to avoid Clang/LLVM assembly issues on Darwin hosts.
$(package)_bootstrap_file_darwin_aarch64=rust-1.75.0-aarch64-apple-darwin.tar.gz
$(package)_bootstrap_sha256_darwin_aarch64=878ecf81e059507dd2ab256f59629a4fb00171035d2a2f5638cb582d999373b1

$(package)_bootstrap_file_darwin_x86_64=rust-1.75.0-x86_64-apple-darwin.tar.gz
$(package)_bootstrap_sha256_darwin_x86_64=ad066e4dec7ae5948c4e7afe68e250c336a5ab3d655570bb119b3eba9cf22851

# Cross-compilation Standard Libraries (re-distributed under MIT/Apache-2.0)
$(package)_std_android=rust-std-1.75.0-aarch64-linux-android.tar.gz
$(package)_std_windows=rust-std-1.75.0-x86_64-pc-windows-gnu.tar.gz
$(package)_std_darwin_arm64=rust-std-1.75.0-aarch64-apple-darwin.tar.gz
$(package)_std_darwin_x86=rust-std-1.75.0-x86_64-apple-darwin.tar.gz
$(package)_std_ios=rust-std-1.75.0-aarch64-apple-ios.tar.gz

# Verified Hashes
$(package)_sha256_hash_rust-std-1.75.0-aarch64-linux-android.tar.gz=1cd6510dd282de87d9247b09f8f90e533393a83385d99151f9ec7983118d299a
$(package)_sha256_hash_rust-std-1.75.0-x86_64-pc-windows-gnu.tar.gz=6c40c5274c8ab13e1c23c9082bc85772330b6a8ca2407a3253b6430239764602
$(package)_sha256_hash_rust-std-1.75.0-aarch64-apple-darwin.tar.gz=8eedd403d05829369e3dd84c6815f69fb7e5495d3ee3bf2b4b2f04d8591fe639
$(package)_sha256_hash_rust-std-1.75.0-x86_64-apple-darwin.tar.gz=65098155333de2e446df61cdaf12a0c441358b7973f3cb1ba95fd11bda890406
$(package)_sha256_hash_rust-std-1.75.0-aarch64-apple-ios.tar.gz=0a7d3ecd36b4be381eabeb84d1df2aa2f9dbce01a9c2029aaa3a38d54eea11a8

ifeq ($(host_os),darwin)
  ifeq ($(host_arch),aarch64)
    $(package)_bootstrap_file=$($(package)_bootstrap_file_darwin_aarch64)
    $(package)_bootstrap_sha256=$($(package)_bootstrap_sha256_darwin_aarch64)
  else ifeq ($(host_arch),x86_64)
    $(package)_bootstrap_file=$($(package)_bootstrap_file_darwin_x86_64)
    $(package)_bootstrap_sha256=$($(package)_bootstrap_sha256_darwin_x86_64)
  else
    $(error Unsupported macOS architecture: $(host_arch). Only aarch64 and x86_64 are supported.)
  endif
else
  $(package)_bootstrap_file=$($(package)_bootstrap_file_linux)
  $(package)_bootstrap_sha256=$($(package)_bootstrap_sha256_linux)
endif

define $(package)_set_vars
$(package)_config_opts = --prefix=$(build_prefix) --disable-ldconfig
endef

define $(package)_config_cmds
    mkdir -p bootstrap && \
    tar -C bootstrap -xf $(SOURCES_PATH)/$($(package)_bootstrap_file) --strip-components=1 && \
    ./bootstrap/install.sh --destdir=$$(PWD)/bootstrap_install --prefix=/ && \
    echo "# Generated by monero_c depends system - do not edit manually" > config.toml && \
    echo "[build]" >> config.toml && \
    echo "rustc = \"$$(PWD)/bootstrap_install/bin/rustc\"" >> config.toml && \
    echo "cargo = \"$$(PWD)/bootstrap_install/bin/cargo\"" >> config.toml && \
    echo "full-bootstrap = false" >> config.toml && \
    echo "[install]" >> config.toml && \
    echo "prefix = \"$(build_prefix)\"" >> config.toml && \
    echo "[rust]" >> config.toml && \
    echo "channel = \"stable\"" >> config.toml && \
    echo "description = \"Bootstrapped via monero_c depends\"" >> config.toml
endef

ifneq ($(host_os),darwin)
define $(package)_build_cmds
    python3 x.py build --stage 1 library/std
endef
else
# macOS/iOS: Use prebuilt bootstrap binary to avoid host-specific build failures.
# This provides a verifiable, reproducible toolchain using official upstream artifacts.
# No source build is performed on Darwin hosts due to Clang/LLVM assembly incompatibilities.
define $(package)_build_cmds
    echo "[llvm]" >> config.toml && \
    echo "ninja = false" >> config.toml && \
    echo "Skipping source build on Darwin. Using verified prebuilt binaries."
endef
endif

define $(package)_stage_cmds
    mkdir -p extra_dist_binary && \
    tar -C extra_dist_binary -xf $(SOURCES_PATH)/$($(package)_bootstrap_file) --strip-components=1 && \
    ./extra_dist_binary/install.sh --destdir=$($(package)_staging_dir) --prefix=$(build_prefix) --disable-ldconfig && \
    mkdir -p extra_dist && \
    tar -C extra_dist -xf $(SOURCES_PATH)/$($(package)_std_android) && \
    extra_dist/rust-std-1.75.0-aarch64-linux-android/install.sh --destdir=$($(package)_staging_dir) --prefix=$(build_prefix) --disable-ldconfig && \
    rm -rf extra_dist/* && \
    tar -C extra_dist -xf $(SOURCES_PATH)/$($(package)_std_windows) && \
    extra_dist/rust-std-1.75.0-x86_64-pc-windows-gnu/install.sh --destdir=$($(package)_staging_dir) --prefix=$(build_prefix) --disable-ldconfig && \
    rm -rf extra_dist/* && \
    tar -C extra_dist -xf $(SOURCES_PATH)/$($(package)_std_darwin_arm64) && \
    extra_dist/rust-std-1.75.0-aarch64-apple-darwin/install.sh --destdir=$($(package)_staging_dir) --prefix=$(build_prefix) --disable-ldconfig && \
    rm -rf extra_dist/* && \
    tar -C extra_dist -xf $(SOURCES_PATH)/$($(package)_std_darwin_x86) && \
    extra_dist/rust-std-1.75.0-x86_64-apple-darwin/install.sh --destdir=$($(package)_staging_dir) --prefix=$(build_prefix) --disable-ldconfig && \
    rm -rf extra_dist/* && \
    tar -C extra_dist -xf $(SOURCES_PATH)/$($(package)_std_ios) && \
    extra_dist/rust-std-1.75.0-aarch64-apple-ios/install.sh --destdir=$($(package)_staging_dir) --prefix=$(build_prefix) --disable-ldconfig && \
    rm -rf extra_dist extra_dist_binary
endef
