name: full compatibility check
on: [push]
permissions:
  issues: write
  pull-requests: write

jobs:
  build_deps:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            container: ubuntu:24.04
            target: mingw
            host_abi: [x86_64-w64-mingw32, i686-w64-mingw32]
            packages: pigz build-essential pkg-config autoconf libtool ccache make cmake gcc g++ git curl lbzip2 gperf gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 gcc-mingw-w64-i686 g++-mingw-w64-i686
          - os: ubuntu-22.04 
            target: android
            host_abi: [x86_64-linux-android, aarch64-linux-android, armv7a-linux-androideabi]
            packages: llvm pigz build-essential pkg-config autoconf libtool ccache make cmake gcc g++ git curl lbzip2 libtinfo6 gperf unzip python-is-python3
          - os: ubuntu-latest
            container: debian:bullseye
            target: linux
            host_abi: [x86_64-linux-gnu, aarch64-linux-gnu, i686-linux-gnu]
            packages: pigz build-essential pkg-config autoconf libtool ccache make cmake gcc g++ git curl lbzip2 libtinfo5 gperf gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-i686-linux-gnu g++-i686-linux-gnu
          - os: macos-15
            target: macos
            host_abi: [aarch64-apple-darwin, x86_64-apple-darwin]
            packages: ccache binutils pigz autoconf automake libtool pkg-config
          - os: macos-15
            target: ios
            host_abi: [aarch64-apple-ios, aarch64-apple-iossimulator]
            packages: ccache cmake autoconf automake libtool

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - name: Free Disk Space (Ubuntu)
        if: ${{ matrix.target == 'android' }}
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Install dependencies
        run: |
          if [ "${{ matrix.container }}" != "" ]; then
            apt update
            apt install -y ${{ matrix.packages }}
          else
            brew install ${{ matrix.packages }}
          fi

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: maxim-lobanov/setup-xcode@v1
        if: ${{ matrix.target == 'macos' || matrix.target == 'ios' }}
        with:
          xcode-version: '16.1'

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: deps-${{ matrix.target }}

      - name: Build dependencies
        run: |
          for host in ${{ join(matrix.host_abi, ' ') }}; do
            pushd contrib/depends
            env -i PATH="$PATH" CC=gcc CXX=g++ make -j$(nproc || sysctl -n hw.logicalcpu) HOST="$host"
            popd
          done

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: contrib/depends/built
          key: deps-${{ matrix.target }}-${{ hashFiles('contrib/depends/packages/*.mk') }}

  build_coins:
    needs: build_deps
    strategy:
      fail-fast: false
      matrix:
        target:
          - name: mingw
            os: ubuntu-latest
            container: ubuntu:24.04
            packages: pigz build-essential pkg-config autoconf libtool ccache make cmake gcc g++ git curl lbzip2 gperf gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 gcc-mingw-w64-i686 g++-mingw-w64-i686
            coins: [monero, wownero]
          - name: android
            os: ubuntu-22.04
            packages: llvm pigz build-essential pkg-config autoconf libtool ccache make cmake gcc g++ git curl lbzip2 libtinfo6 gperf unzip python-is-python3
            coins: [monero, wownero, zano]
          - name: linux
            os: ubuntu-latest
            container: debian:bullseye
            packages: pigz build-essential pkg-config autoconf libtool ccache make cmake gcc g++ git curl lbzip2 libtinfo5 gperf gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-i686-linux-gnu g++-i686-linux-gnu
            coins: [monero, wownero, zano]
          - name: macos
            os: macos-15
            packages: ccache binutils pigz autoconf automake libtool pkg-config
            coins: [monero, wownero, zano]
          - name: ios
            os: macos-15
            packages: ccache cmake autoconf automake libtool
            coins: [monero, wownero, zano]
        coin:
          - monero
          - wownero
          - zano
        exclude:
          - target: {name: mingw}
            coin: zano
    runs-on: ${{ matrix.target.os }}
    container: ${{ matrix.target.container }}

    steps:
      - name: Free Disk Space (Ubuntu)
        if: ${{ matrix.target == 'android' }}
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Install dependencies
        run: |
          if [ "$(uname)" = "Linux" ]; then
            apt update
            apt install -y ${{ matrix.target.packages }}
          else
            brew install ${{ matrix.target.packages }}
          fi

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: maxim-lobanov/setup-xcode@v1
        if: ${{ matrix.target.os == 'macos' || matrix.target.os == 'ios' }}
        with:
          xcode-version: ${{ matrix.target.os == 'macos' && '15.4' || '16.1' }}

      - name: Patch sources
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "ci@mrcyjanek.net"
          git config --global user.name "CI mrcyjanek.net"
          ./apply_patches.sh ${{ matrix.coin }}

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.target }}-${{ matrix.coin }}

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: contrib/depends/built
          key: deps-${{ matrix.target }}-${{ hashFiles('contrib/depends/packages/*.mk') }}

      - name: Build ${{ matrix.coin }}
        run: |
          case ${{ matrix.target }} in
            mingw)
              ./build_single.sh ${{ matrix.coin }} x86_64-w64-mingw32 -j$(nproc)
              ./build_single.sh ${{ matrix.coin }} i686-w64-mingw32 -j$(nproc)
              ;;
            android)
              ./build_single.sh ${{ matrix.coin }} x86_64-linux-android -j$(nproc)
              ./build_single.sh ${{ matrix.coin }} aarch64-linux-android -j$(nproc)
              ./build_single.sh ${{ matrix.coin }} armv7a-linux-androideabi -j$(nproc)
              ;;
            linux)
              ./build_single.sh ${{ matrix.coin }} x86_64-linux-gnu -j$(nproc)
              ./build_single.sh ${{ matrix.coin }} aarch64-linux-gnu -j$(nproc)
              ./build_single.sh ${{ matrix.coin }} i686-linux-gnu -j$(nproc)
              ;;
            macos)
              ./build_single.sh ${{ matrix.coin }} aarch64-apple-darwin -j$(sysctl -n hw.logicalcpu)
              ./build_single.sh ${{ matrix.coin }} x86_64-apple-darwin -j$(sysctl -n hw.logicalcpu)
              ;;
            ios)
              ./build_single.sh ${{ matrix.coin }} aarch64-apple-ios -j$(sysctl -n hw.logicalcpu)
              ./build_single.sh ${{ matrix.coin }} aarch64-apple-iossimulator -j$(sysctl -n hw.logicalcpu)
              ;;
          esac

      - name: rename artifacts
        run: |
          mkdir release/gh/
          for i in release/${{ matrix.coin }}/*
          do
              cp "$i" "release/gh/${{ matrix.coin }}_$(basename $i)"
          done

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/gh/*
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Upload lib
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }} ${{ matrix.coin }}
          path: release/${{ matrix.coin }}

      - name: remove android_ndk
        if: ${{ matrix.target == 'android' }}
        run: |
          rm -rf contrib/depends/built/*/android_ndk
          rm -rf contrib/depends/sources/android-ndk-r26d-linux.zip

  bulk_lib_release:
    name: create single release file
    runs-on: ubuntu-latest
    needs: [build_coins]
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: "* *"
          path: release
          merge-multiple: true

      - name: zip release dir
        run: zip -r release-bundle.zip release

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release-bundle.zip
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Upload lib
        uses: actions/upload-artifact@v4
        with:
          name: release-bulk
          path: release

  # Test jobs remain the same
  deno_monerots_test_linux:
    name: test ts library
    runs-on: ubuntu-24.04
    needs: [build_coins]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/download-artifact@v4
        with:
          name: linux monero
          path: release/monero
      - name: unpack and move monero_c
        run: |
          unxz -f -k release/*/*.xz
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Create symlink
        run: |
          cd impls/monero.ts
          mkdir lib
          cd lib
          ln -s ../../../release/monero/x86_64-linux-gnu_libwallet2_api_c.so
          mv x86_64-linux-gnu_libwallet2_api_c.so monero_libwallet2_api_c.so
          cd ..
      - name: Run tests
        run: |
          cd impls/monero.ts
          deno run --unstable-ffi --allow-ffi checksum.ts

  regression_tests_linux:
    name: linux regression tests
    strategy:
      fail-fast: false
      matrix:
        coin: [monero, wownero]
    needs: [build_coins]
    runs-on: ubuntu-24.04
    steps:
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions/download-artifact@v4
        with:
          name: linux ${{ matrix.coin }}
          path: release/${{ matrix.coin }}

      - name: Run regression tests
        run: COIN="${{ matrix.coin }}" deno test -A tests/regression.test.ts

  regression_tests_macos:
    name: macos regression tests
    strategy:
      matrix:
        coin: [monero, wownero]
    needs: [build_coins]
    runs-on: macos-15
    steps:
      - uses: denoland/setup-deno@v2
        with:
          deno-version: canary

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions/download-artifact@v4
        with:
          name: macos ${{ matrix.coin }}
          path: release/${{ matrix.coin }}

      - name: Run regression tests
        run: COIN="${{ matrix.coin }}" deno test -A tests/regression.test.ts

  integration_tests_linux:
    name: linux integration tests
    strategy:
      matrix:
        coin: [monero, wownero]
    needs: [build_coins]
    runs-on: ubuntu-24.04
    steps:
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions/download-artifact@v4
        with:
          name: linux ${{ matrix.coin }}
          path: release/${{ matrix.coin }}

      - name: Run integration tests
        run: COIN="${{ matrix.coin }}" deno test -A tests/integration.test.ts
        env:
          SECRET_WALLET_PASSWORD: ${{ secrets.SECRET_WALLET_PASSWORD }}
          SECRET_WALLET_MNEMONIC: ${{ secrets.SECRET_WALLET_MNEMONIC }}
          SECRET_WALLET_RESTORE_HEIGHT: ${{ secrets.SECRET_WALLET_RESTORE_HEIGHT }}

  integration_tests_macos:
    name: macos integration tests
    strategy:
      matrix:
        coin: [monero, wownero]
    needs: [build_coins]
    runs-on: macos-15
    steps:
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions/download-artifact@v4
        with:
          name: macos ${{ matrix.coin }}
          path: release/${{ matrix.coin }}

      - name: Run integration tests
        run: COIN="${{ matrix.coin }}" deno test -A tests/integration.test.ts
        env:
          SECRET_WALLET_PASSWORD: ${{ secrets.SECRET_WALLET_PASSWORD }}
          SECRET_WALLET_MNEMONIC: ${{ secrets.SECRET_WALLET_MNEMONIC }}
          SECRET_WALLET_RESTORE_HEIGHT: ${{ secrets.SECRET_WALLET_RESTORE_HEIGHT }}

  comment_pr:
    name: comment on pr
    runs-on: ubuntu-latest
    needs: [build_coins]
    steps:
      - uses: actions/github-script@v7
        continue-on-error: true
        id: get_issue_number
        with:
          script: |
            if (context.issue.number) {
              return context.issue.number;
            } else {
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
            }
          result-encoding: string
      - name: Find Comment
        continue-on-error: true
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{steps.get_issue_number.outputs.result}}
          comment-author: 'github-actions[bot]'
          body-includes: download artifacts
      - name: Update comment
        continue-on-error: true
        if: steps.fc.outcome == 'success'
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{steps.get_issue_number.outputs.result}}
          body: |
            [download artifacts #${{github.run_id}}](https://nightly.link/MrCyjaneK/monero_c/actions/runs/${{github.run_id}})
          edit-mode: replace
      - name: Create comment
        continue-on-error: true
        if: steps.fc.outcome == 'failure'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{steps.get_issue_number.outputs.result}}
          body: |
            [download artifacts #${{github.run_id}}](https://nightly.link/MrCyjaneK/monero_c/actions/runs/${{github.run_id}}) (this comment will update whenever you push)